# -*- coding: utf-8 -*-
"""24_Matrix Multiplication.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ScZiyQnH4RmQdA923rq0fi6diquZj1xp
"""

1 buat matrix A dengan ukuran 2x3 dan vector b berukuran 3x1 menggunakan numpy
buat matrix A_pt dengan ukuran 2x3 dan vector b_pt berukuran 3x1 menggunakan pytorch
buat matrix A_tf dengan ukuran 2x3 dan vector b_tf berukuran 3x1 menggunakan tensorflow
2 tampilkan ukuran matrix A dan vector b
3 kalikan matrix A dengan vector b
kalikan matrix A_pt dengan vector b_pt
kalikan matrix A_tf dengan vector b_tf
4 buat matrix B dengan ukuran 3x3 menggunakan numpy
buat matrix B_pt dengan ukuran 3x3 menggunakan pytorch
buat matrix B_tf dengan ukuran 3x3 menggunakan tensorflow
5 kalikan matrix A dengan matrix B
kalikan matrix A_pt dengan matrix B_pt
kalikan matrix A_tf dengan matrix B_tf
6 buktikan apakah perkalian matrix bersifat komutatif? (AB=BA)?

import numpy as np
import torch
import tensorflow as tf

1

# membuat matrix A dengan ukuran 2x3 dan vector b berukuran 3x1 menggunakan numpy

A = np.array([[1, 2, 3],
              [4, 5, 6]])
A

b = np.array([[7],
              [8],
              [9]])
b

# membuat matrix A_pt dengan ukuran 2x3 dan vector b_pt berukuran 3x1 menggunakan pytor

A_pt = torch.tensor([[1, 2, 3],
              [4, 5, 6]])
A_pt

b_pt = torch.tensor([[7],
                     [8],
                     [9]])
b_pt

# membuat matrix A_tf dengan ukuran 2x3 dan vector b_tf berukuran 3x1 menggunakan tensorflow

A_tf = tf.Variable([[1, 2, 3],
                    [4, 5, 6]])
A_tf

b_tf = tf.Variable([[7],
                    [8],
                    [9]])
b_tf

2

# menampilkan ukuran matrix A dan vector b

import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])

b= np.array([[7],
              [8],
              [9]])

print("Ukuran matriks A:", A.shape)
print("Ukuran vektor b:", b.shape)

3

# mengalikan matrix A dengan vector b

A = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([[7],
              [8],
              [9]])

np.dot(A, b)

# mengalikan matrix A_pt dengan vector b_pt

import torch

A_pt = torch.tensor([[1, 2, 3],
                     [4, 5, 6]])

b_pt = torch.tensor([[7],
                     [8],
                     [9]])

il = torch.matmul(A_pt, b_pt)
print(hasil)

# mengalikan matrix A_tf dengan vector b_tf

import tensorflow as tf

A_tf = tf.Variable([[1, 2, 3],
                    [4, 5, 6]])

b_tf = tf.Variable([[7],
                    [8],
                    [9]])

hasil = tf.matmul(A_tf, b_tf)
print(hasil)

4

# membuat matrix B dengan ukuran 3x3 menggunakan numpy

import numpy as np

B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B

# membuat matrix B_pt dengan ukuran 3x3 menggunakan pytorch

import torch

B_pt = torch.tensor([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

B_pt

# membuat matrix B_tf dengan ukuran 3x3 menggunakan tensorflow

import tensorflow as tf

B_tf = tf.constant([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

B_tf

5

# mengalikan matrix A dengan matrix B

import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])
A

B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B


np.dot(A, B)

# mengalikan matrix A_pt dengan matrix B_pt

import torch

A_pt = torch.tensor([[1, 2, 3],
              [4, 5, 6]])
A_pt

B_pt = torch.tensor([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])
B_pt

hasil = torch.matmul(A_pt, B_pt)
print(hasil)

# mengalikan matrix A_tf dengan matrix B_tf

import tensorflow as tf

A_tf = tf.Variable([[1, 2, 3],
                    [4, 5, 6]])
A_tf

B_tf = tf.constant([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
B_tf

hasil = tf.matmul(A_tf, B_tf)
print(hasil)

6

# membuktikan apakah perkalian matrix bersifat komutatif? (AB=BA)?

import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B

print("Hasil perkalian A × B:\n", np.dot(A, B))
try:
    print("Hasil kalikan matrix B dengan matrix A: \n",np.dot(B, A))
except ValueError as e:
    print("\nBA tidak bisa dihitung:")
    print(e)
'''Perkalian matriks tidak bersifat komutatif (AB ≠ BA), karena:
1. Tidak semua pasangan matriks dapat dikalikan dalam kedua urutan (AB bisa tetapi BA tidak, atau sebaliknya)
2. Meskipun kedua perkalian terdefinisi, hasilnya belum tentu sama)'''